### ISSUE TITLE
기프티콘 구매 시에 file not found error

### ISSUE THREAD

**Issue by k-young-passionate** [2019-iuc-sw-skku/Lambda256#8]
다음과 같이 400 에러가 뜨는데 error_code 를 확인할 수 없습니다.

어디서 난 에러인지 확인할 수 있도록 조치 부탁드립니다.

ex) responseCode 를 다르게 혹은 Message를 다르게

![image](https://user-images.githubusercontent.com/11757075/68238284-38e0ea00-004c-11ea-9482-59b47a75dbc0.png)

**Comment by Orb-H** [comment]
response에 error_code가 포함되지 않았나요??

**Comment by k-young-passionate** [comment]
추측건데 기프티콘과 연결된 이미지가 없는게 문제이지 않을까 싶습니다. 확인 부탁드립니다.

**Comment by k-young-passionate** [comment]
아 내용물이 확인되지 않는건 제 실수였네요.
Exception 발생 시 getInputStream 이 아닌 getErrorStream 을 쓰면 잘 보입니다.
코드가 5번이 날아오네요...
(이미 사용한 TX hash)

**Comment by k-young-passionate** [comment]
이제는 500이 뜨고 JSON 파일이 안오고 다음과 같은 메시지가 옵니다.
Cannot read property 'history' of undefined

**Comment by Orb-H** [comment]
이건 API가 v1.1로 업데이트하면서 문제가 생기는 것 같습니다. 버전 업그레이드하면서 바뀐 API 호출 변수를 파악하고 주소와 변수를 해당 버전에 맞게 바꿔야 할 것으로 보입니다.

**Comment by Orb-H** [comment]
API 호출 변수에 있어서는 달라진 점이 없는 것 같아서 API 호출 주소만 바꾸고 푸시했습니다
